import { db } from "@/lib/drizzle/db";
import { grammars } from "@/lib/drizzle/seed/schema";

export async function InsertN4Grammars() {
  return await db.insert(grammars).values([
    {
      id: "N4_1",
      romajiRead: "aida",
      japaneseRead: "間",
      level: "N4",
      explain: ``,
      meaning: "Trong khi/suốt trong/giữa...",
      usingWay: ``,
    },
    {
      id: "N4_2",
      romajiRead: "aida ni",
      japaneseRead: "間に",
      level: "N4",
      explain: ``,
      meaning: "Trong khi/trong lúc/trong khoảng...",
      usingWay: ``,
    },
    {
      id: "N4_3",
      romajiRead: "atode",
      japaneseRead: "あとで",
      level: "N4",
      explain: ``,
      meaning: "Sau đó...",
      usingWay: ``,
    },
    {
      id: "N4_4",
      romajiRead: "ba～hodo",
      japaneseRead: "ば～ほど",
      level: "N4",
      explain: ``,
      meaning: "Càng...càng...",
      usingWay: ``,
    },
    {
      id: "N4_5",
      romajiRead: "baai wa",
      japaneseRead: "場合は",
      level: "N4",
      explain: ``,
      meaning: "Trong trường hợp.../khi...",
      usingWay: ``,
    },
    {
      id: "N4_6",
      romajiRead: "bakari desu",
      japaneseRead: "ばかりです",
      level: "N4",
      explain: ``,
      meaning: "Vừa mới...",
      usingWay: ``,
    },
    {
      id: "N4_7",
      romajiRead: "dake de",
      japaneseRead: "だけで",
      level: "N4",
      explain: ``,
      meaning: "Chỉ cần...",
      usingWay: ``,
    },
    {
      id: "N4_8",
      romajiRead: "dasu",
      japaneseRead: "出す",
      level: "N4",
      explain: ``,
      meaning: "Bắt đầu/đột nhiên...",
      usingWay: ``,
    },
    {
      id: "N4_9",
      romajiRead: "de",
      japaneseRead: "で",
      level: "N4",
      explain: ``,
      meaning: "Bằng/với...",
      usingWay: ``,
    },
    {
      id: "N4_10",
      romajiRead: "de gozaimasu",
      japaneseRead: "でございます",
      level: "N4",
      explain: ``,
      meaning: "Là(kính ngữ)...",
      usingWay: ``,
    },
    {
      id: "N4_11",
      romajiRead: "deshou",
      japaneseRead: "でしょう",
      level: "N4",
      explain: ``,
      meaning: "Có lẽ/chắc hẳn",
      usingWay: ``,
    },
    {
      id: "N4_12",
      romajiRead: "ga hitsuyou",
      japaneseRead: "が必要",
      level: "N4",
      explain: ``,
      meaning: "Cần..",
      usingWay: ``,
    },
    {
      id: "N4_13",
      romajiRead: "ga suru",
      japaneseRead: "がする",
      level: "N4",
      explain: ``,
      meaning: "Có(mùi/tiếng/cảm giác...)",
      usingWay: ``,
    },
    {
      id: "N4_14",
      romajiRead: "gari",
      japaneseRead: "がり",
      level: "N4",
      explain: ``,
      meaning: "Có xu hướng/dễ trở nên...",
      usingWay: ``,
    },
    {
      id: "N4_15",
      romajiRead: "hajimeru",
      japaneseRead: "始める",
      level: "N4",
      explain: ``,
      meaning: "Bắt đầu...",
      usingWay: ``,
    },
    {
      id: "N4_16",
      romajiRead: "hazu desu",
      japaneseRead: "はずです",
      level: "N4",
      explain: ``,
      meaning: "Chắc chắn",
      usingWay: ``,
    },
    {
      id: "N4_17",
      romajiRead: "hitsuyou ga aru",
      japaneseRead: "必要がある",
      level: "N4",
      explain: ``,
      meaning: "Cần/cần phải...",
      usingWay: ``,
    },
    {
      id: "N4_18",
      romajiRead: "hou ga ii",
      japaneseRead: "ほうがいい",
      level: "N4",
      explain: ``,
      meaning: "Nên/không nên",
      usingWay: ``,
    },
    {
      id: "N4_19",
      romajiRead: "ii desuka",
      japaneseRead: "いいですか",
      level: "N4",
      explain: ``,
      meaning: "...phải làm thế nào？",
      usingWay: ``,
    },
    {
      id: "N4_20",
      romajiRead: "ikou kei",
      japaneseRead: "意向形",
      level: "N4",
      explain: ``,
      meaning: "Thể ý định, ý hướng",
      usingWay: ``,
    },
    {
      id: "N4_21",
      romajiRead: "ippou da",
      japaneseRead: "一方だ",
      level: "N4",
      explain: ``,
      meaning: "Ngày càng...",
      usingWay: ``,
    },
    {
      id: "N4_22",
      romajiRead: "irassharu",
      japaneseRead: "いらっしゃる",
      level: "N4",
      explain: ``,
      meaning: "Đi/đến/ở/có...",
      usingWay: ``,
    },
    {
      id: "N4_23",
      romajiRead: "itadakemasen ka",
      japaneseRead: "いただけませんか",
      level: "N4",
      explain: ``,
      meaning: "Cho phép...được không？",
      usingWay: ``,
    },
    {
      id: "N4_24",
      romajiRead: "itadakemasen ka",
      japaneseRead: "いただけませんか",
      level: "N4",
      explain: ``,
      meaning: "Cho tôi...có được không？",
      usingWay: ``,
    },
    {
      id: "N4_25",
      romajiRead: "itashimasu",
      japaneseRead: "いたします",
      level: "N4",
      explain: ``,
      meaning: "Làm (dạng lịch sự của する)...",
      usingWay: ``,
    },
    {
      id: "N4_26",
      romajiRead: "jouken kei",
      japaneseRead: "条件形",
      level: "N4",
      explain: ``,
      meaning: "Thể điều kiện",
      usingWay: ``,
    },
    {
      id: "N4_27",
      romajiRead: "ka",
      japaneseRead: "か",
      level: "N4",
      explain: ``,
      meaning: "Không...？",
      usingWay: ``,
    },
    {
      id: "N4_28",
      romajiRead: "ka douka",
      japaneseRead: "かどうか",
      level: "N4",
      explain: ``,
      meaning: "hay không？",
      usingWay: ``,
    },
    {
      id: "N4_29",
      romajiRead: "kamo shiremasen",
      japaneseRead: "かもしれません",
      level: "N4",
      explain: ``,
      meaning: "Không chừng/có thể",
      usingWay: ``,
    },
    {
      id: "N4_30",
      romajiRead: "kanou kei",
      japaneseRead: "可能形",
      level: "N4",
      explain: ``,
      meaning: "Thể khả năng",
      usingWay: ``,
    },
    {
      id: "N4_31",
      romajiRead: "kara tsukuri masu",
      japaneseRead: "からつくります",
      level: "N4",
      explain: ``,
      meaning: "Làm từ/bằng...",
      usingWay: ``,
    },
    {
      id: "N4_32",
      romajiRead: "kashira",
      japaneseRead: "かしら",
      level: "N4",
      explain: ``,
      meaning: "Không biết là.../phân vân là...",
      usingWay: ``,
    },
    {
      id: "N4_33",
      romajiRead: "kenjou go",
      japaneseRead: "謙譲語",
      level: "N4",
      explain: ``,
      meaning: "Thể khiêm nhường ngữ",
      usingWay: ``,
    },
    {
      id: "N4_34",
      romajiRead: "kinshi kei",
      japaneseRead: "禁止形",
      level: "N4",
      explain: ``,
      meaning: "Thể cấm chỉ",
      usingWay: ``,
    },
    {
      id: "N4_35",
      romajiRead: "kitto",
      japaneseRead: "きっと",
      level: "N4",
      explain: ``,
      meaning: "Chắc chắn...",
      usingWay: ``,
    },
    {
      id: "N4_36",
      romajiRead: "koro",
      japaneseRead: "頃",
      level: "N4",
      explain: ``,
      meaning: "Khoảng/tầm...",
      usingWay: ``,
    },
    {
      id: "N4_37",
      romajiRead: "kudasai masenka",
      japaneseRead: "くださいませんか",
      level: "N4",
      explain: ``,
      meaning: "Có được không...",
      usingWay: ``,
    },
    {
      id: "N4_38",
      romajiRead: "kusuru",
      japaneseRead: "くする",
      level: "N4",
      explain: ``,
      meaning: "Làm cho...",
      usingWay: ``,
    },
    {
      id: "N4_39",
      romajiRead: "kyuu ni",
      japaneseRead: "急に",
      level: "N4",
      explain: ``,
      meaning: "Đột nhiên/đột ngột/bất ngờ....",
      usingWay: ``,
    },
    {
      id: "N4_40",
      romajiRead: "mada",
      japaneseRead: "まだ",
      level: "N4",
      explain: ``,
      meaning: "Vẫn/vẫn còn...",
      usingWay: ``,
    },
    {
      id: "N4_41",
      romajiRead: "mada～imasen",
      japaneseRead: "まだ～いません",
      level: "N4",
      explain: ``,
      meaning: "Vẫn chưa...",
      usingWay: ``,
    },
    {
      id: "N4_42",
      romajiRead: "matawa",
      japaneseRead: "または",
      level: "N4",
      explain: ``,
      meaning: "Hoặc là...",
      usingWay: ``,
    },
    {
      id: "N4_43",
      romajiRead: "meirei kei",
      japaneseRead: "命令形",
      level: "N4",
      explain: ``,
      meaning: "Thể mệnh lệnh",
      usingWay: ``,
    },
    {
      id: "N4_44",
      romajiRead: "mo",
      japaneseRead: "も",
      level: "N4",
      explain: ``,
      meaning: "Đến/đến mức...",
      usingWay: ``,
    },
    {
      id: "N4_45",
      romajiRead: "moshika shitara",
      japaneseRead: "もしかしたら",
      level: "N4",
      explain: ``,
      meaning: "Có thể là/hoặc là/biết đâu...",
      usingWay: ``,
    },
    {
      id: "N4_46",
      romajiRead: "n desu",
      japaneseRead: "んです",
      level: "N4",
      explain: ``,
      meaning: "Vì/bởi vì...",
      usingWay: ``,
    },
    {
      id: "N4_47",
      romajiRead: "n desu ga",
      japaneseRead: "んですが",
      level: "N4",
      explain: ``,
      meaning: "Ý tôi là/nhưng",
      usingWay: ``,
    },
    {
      id: "N4_48",
      romajiRead: "nagara",
      japaneseRead: "ながら",
      level: "N4",
      explain: ``,
      meaning: "Vừa...vừa",
      usingWay: ``,
    },
    {
      id: "N4_49",
      romajiRead: "nai de",
      japaneseRead: "ないで",
      level: "N4",
      explain: ``,
      meaning: "Mà không...",
      usingWay: ``,
    },
    {
      id: "N4_50",
      romajiRead: "naku te",
      japaneseRead: "なくて",
      level: "N4",
      explain: ``,
      meaning: "Vì/sau khi...",
      usingWay: ``,
    },
    {
      id: "N4_51",
      romajiRead: "nara",
      japaneseRead: "なら",
      level: "N4",
      explain: ``,
      meaning: "Nếu mà/nếu là",
      usingWay: ``,
    },
    {
      id: "N4_52",
      romajiRead: "nasai",
      japaneseRead: "なさい",
      level: "N4",
      explain: ``,
      meaning: "Hãy...",
      usingWay: ``,
    },
    {
      id: "N4_53",
      romajiRead: "nasaru",
      japaneseRead: "なさる",
      level: "N4",
      explain: ``,
      meaning: "Làm/thực hiện (kính ngữ)...",
      usingWay: ``,
    },
    {
      id: "N4_54",
      romajiRead: "ni ki ga tsuku",
      japaneseRead: "に気がつく",
      level: "N4",
      explain: ``,
      meaning: "Nhận thấy/chợt nhận ra...",
      usingWay: ``,
    },
    {
      id: "N4_55",
      romajiRead: "ni mieru",
      japaneseRead: "にみえる",
      level: "N4",
      explain: ``,
      meaning: "Trông giống như...",
      usingWay: ``,
    },
    {
      id: "N4_56",
      romajiRead: "ni suru",
      japaneseRead: "にする",
      level: "N4",
      explain: ``,
      meaning: "Chọn/quyết định làm gì đó.",
      usingWay: ``,
    },
    {
      id: "N4_57",
      romajiRead: "ni yotte",
      japaneseRead: "によって",
      level: "N4",
      explain: ``,
      meaning: "Do/bởi...",
      usingWay: ``,
    },
    {
      id: "N4_58",
      romajiRead: "nikui desu",
      japaneseRead: "にくいです",
      level: "N4",
      explain: ``,
      meaning: "Khó...",
      usingWay: ``,
    },
    {
      id: "N4_59",
      romajiRead: "no wo shitte imasu ka",
      japaneseRead: "のを知っていますか",
      level: "N4",
      explain: ``,
      meaning: "Có biết...hay không？",
      usingWay: ``,
    },
    {
      id: "N4_60",
      romajiRead: "no wo wasureta",
      japaneseRead: "のを忘れた",
      level: "N4",
      explain: ``,
      meaning: "Quên...",
      usingWay: ``,
    },
    {
      id: "N4_61",
      romajiRead: "node",
      japaneseRead: "ので",
      level: "N4",
      explain: ``,
      meaning: "Vì là/do..",
      usingWay: ``,
    },
    {
      id: "N4_62",
      romajiRead: "noga suki",
      japaneseRead: "のが好き",
      level: "N4",
      explain: ``,
      meaning: "Thích làm gì đó...",
      usingWay: ``,
    },
    {
      id: "N4_63",
      romajiRead: "noga∼desu",
      japaneseRead: "のが～です",
      level: "N4",
      explain: ``,
      meaning: "Thì.../Là...",
      usingWay: ``,
    },
    {
      id: "N4_64",
      romajiRead: "noni",
      japaneseRead: "のに",
      level: "N4",
      explain: ``,
      meaning: "Thế mà/vậy mà...",
      usingWay: ``,
    },
    {
      id: "N4_65",
      romajiRead: "nowa∼desu",
      japaneseRead: "のは～です",
      level: "N4",
      explain: ``,
      meaning: "Là...",
      usingWay: ``,
    },
    {
      id: "N4_66",
      romajiRead: "oki ni",
      japaneseRead: "おきに",
      level: "N4",
      explain: ``,
      meaning: "Cứ cách...",
      usingWay: ``,
    },
    {
      id: "N4_67",
      romajiRead: "owaru",
      japaneseRead: "終わる",
      level: "N4",
      explain: ``,
      meaning: "Hoàn thành/làm xong...",
      usingWay: ``,
    },
    {
      id: "N4_68",
      romajiRead: "sa",
      japaneseRead: "さ",
      level: "N4",
      explain: ``,
      meaning: "Sự/độ/cái...",
      usingWay: ``,
    },
    {
      id: "N4_69",
      romajiRead: "sakki",
      japaneseRead: "さっき",
      level: "N4",
      explain: ``,
      meaning: "Vừa nãy/lúc nãy...",
      usingWay: ``,
    },
    {
      id: "N4_70",
      romajiRead: "sasuga",
      japaneseRead: "さすが",
      level: "N4",
      explain: ``,
      meaning: "Quả nhiên/quả là...",
      usingWay: ``,
    },
    {
      id: "N4_71",
      romajiRead: "shi~shi",
      japaneseRead: "し～し",
      level: "N4",
      explain: ``,
      meaning: "Vừa...vừa",
      usingWay: ``,
    },
    {
      id: "N4_72",
      romajiRead: "shieki kei",
      japaneseRead: "使役形",
      level: "N4",
      explain: ``,
      meaning: "Thể sai khiến",
      usingWay: ``,
    },
    {
      id: "N4_73",
      romajiRead: "shika∼nai",
      japaneseRead: "しか～ない",
      level: "N4",
      explain: ``,
      meaning: "Chỉ...",
      usingWay: ``,
    },
    {
      id: "N4_74",
      romajiRead: "sonkei go",
      japaneseRead: "尊敬語",
      level: "N4",
      explain: ``,
      meaning: "Tôn kính ngữ",
      usingWay: ``,
    },
    {
      id: "N4_75",
      romajiRead: "sore de",
      japaneseRead: "それで",
      level: "N4",
      explain: ``,
      meaning: "Do đó/vì thế...",
      usingWay: ``,
    },
    {
      id: "N4_76",
      romajiRead: "sore ni",
      japaneseRead: "それに",
      level: "N4",
      explain: ``,
      meaning: "Hơn thế nữa...",
      usingWay: ``,
    },
    {
      id: "N4_77",
      romajiRead: "sore wa",
      japaneseRead: "それは",
      level: "N4",
      explain: ``,
      meaning: "Cái đó/chuyện đó/thế thì...",
      usingWay: ``,
    },
    {
      id: "N4_78",
      romajiRead: "sou desu",
      japaneseRead: "そうです",
      level: "N4",
      explain: ``,
      meaning: "Nghe nói",
      usingWay: ``,
    },
    {
      id: "N4_79",
      romajiRead: "sou desu",
      japaneseRead: "そうです",
      level: "N4",
      explain: ``,
      meaning: "Có vẻ/hình như",
      usingWay: ``,
    },
    {
      id: "N4_80",
      romajiRead: "sugi masu",
      japaneseRead: "すぎます",
      level: "N4",
      explain: ``,
      meaning: "Quá...",
      usingWay: ``,
    },
    {
      id: "N4_81",
      romajiRead: "tabun",
      japaneseRead: "たぶん",
      level: "N4",
      explain: ``,
      meaning: "Có lẽ...",
      usingWay: ``,
    },
    {
      id: "N4_82",
      romajiRead: "tame ni",
      japaneseRead: "ために",
      level: "N4",
      explain: ``,
      meaning: "Để/cho/vì...",
      usingWay: ``,
    },
    {
      id: "N4_83",
      romajiRead: "tara ii desuka",
      japaneseRead: "たらいいですか",
      level: "N4",
      explain: ``,
      meaning: "Nên/phải làm thế nào？",
      usingWay: ``,
    },
    {
      id: "N4_84",
      romajiRead: "te aru",
      japaneseRead: "てある",
      level: "N4",
      explain: ``,
      meaning: "Có làm gì đó",
      usingWay: ``,
    },
    {
      id: "N4_85",
      romajiRead: "te iru",
      japaneseRead: "ている",
      level: "N4",
      explain: ``,
      meaning: "Thường làm gì đó....",
      usingWay: ``,
    },
    {
      id: "N4_86",
      romajiRead: "te kimasu",
      japaneseRead: "て来ます",
      level: "N4",
      explain: ``,
      meaning: "Đi đâu đó rồi về...",
      usingWay: ``,
    },
    {
      id: "N4_87",
      romajiRead: "te mimasu",
      japaneseRead: "てみます",
      level: "N4",
      explain: ``,
      meaning: "Thử làm...",
      usingWay: ``,
    },
    {
      id: "N4_88",
      romajiRead: "te okimasu",
      japaneseRead: "ておきます",
      level: "N4",
      explain: ``,
      meaning: "Làm gì trước...",
      usingWay: ``,
    },
    {
      id: "N4_89",
      romajiRead: "te shimai masu",
      japaneseRead: "てしまいます",
      level: "N4",
      explain: ``,
      meaning: "Xong/lỡ làm...",
      usingWay: ``,
    },
    {
      id: "N4_90",
      romajiRead: "te sumimasen",
      japaneseRead: "てすみません",
      level: "N4",
      explain: ``,
      meaning: "Xin lỗi...",
      usingWay: ``,
    },
    {
      id: "N4_91",
      romajiRead: "te yokatta",
      japaneseRead: "てよかった",
      level: "N4",
      explain: ``,
      meaning: "May quá/may mà đã..",
      usingWay: ``,
    },
    {
      id: "N4_92",
      romajiRead: "teinei go",
      japaneseRead: "丁寧語",
      level: "N4",
      explain: ``,
      meaning: "Thể lịch sự",
      usingWay: ``,
    },
    {
      id: "N4_93",
      romajiRead: "to itte imashita",
      japaneseRead: "と言っていました",
      level: "N4",
      explain: ``,
      meaning: "Đã nói là...",
      usingWay: ``,
    },
    {
      id: "N4_94",
      romajiRead: "to omotte imasu",
      japaneseRead: "と思っています",
      level: "N4",
      explain: ``,
      meaning: "Định làm",
      usingWay: ``,
    },
    {
      id: "N4_95",
      romajiRead: "to tsutaete itadake masenka",
      japaneseRead: "と伝えていただけませんか",
      level: "N4",
      explain: ``,
      meaning: "Có thể...được không？",
      usingWay: ``,
    },
    {
      id: "N4_96",
      romajiRead: "tochuu de",
      japaneseRead: "途中で",
      level: "N4",
      explain: ``,
      meaning: "Trên đường/giữa chừng...",
      usingWay: ``,
    },
    {
      id: "N4_97",
      romajiRead: "toiu imi desu",
      japaneseRead: "という意味です",
      level: "N4",
      explain: ``,
      meaning: "Nghĩa là...",
      usingWay: ``,
    },
    {
      id: "N4_98",
      romajiRead: "toka∼toka",
      japaneseRead: "とか～とか",
      level: "N4",
      explain: ``,
      meaning: "Như là/hoặc là...",
      usingWay: ``,
    },
    {
      id: "N4_99",
      romajiRead: "tokoro desu",
      japaneseRead: "ところです",
      level: "N4",
      explain: ``,
      meaning: "Vừa mới/vừa xong...",
      usingWay: ``,
    },
    {
      id: "N4_100",
      romajiRead: "toori ni",
      japaneseRead: "とおりに",
      level: "N4",
      explain: ``,
      meaning: "Làm theo/như/đúng như...",
      usingWay: ``,
    },
    {
      id: "N4_101",
      romajiRead: "tsumori desu",
      japaneseRead: "つもりです",
      level: "N4",
      explain: ``,
      meaning: "Sẽ/định",
      usingWay: ``,
    },
    {
      id: "N4_102",
      romajiRead: "tsuzukeru",
      japaneseRead: "続ける",
      level: "N4",
      explain: ``,
      meaning: "Tiếp tục...",
      usingWay: ``,
    },
    {
      id: "N4_103",
      romajiRead: "ukemi kei",
      japaneseRead: "受身形",
      level: "N4",
      explain: ``,
      meaning: "Thể bị động",
      usingWay: ``,
    },
    {
      id: "N4_104",
      romajiRead: "wa",
      japaneseRead: "は",
      level: "N4",
      explain: ``,
      meaning: "Tối thiểu/ít nhất là...",
      usingWay: ``,
    },
    {
      id: "N4_105",
      romajiRead: "yasui desu",
      japaneseRead: "やすいです",
      level: "N4",
      explain: ``,
      meaning: "Dễ...",
      usingWay: ``,
    },
    {
      id: "N4_106",
      romajiRead: "yatto",
      japaneseRead: "やっと",
      level: "N4",
      explain: ``,
      meaning: "Cuối cùng thì...",
      usingWay: ``,
    },
    {
      id: "N4_107",
      romajiRead: "yotei desu",
      japaneseRead: "予定です",
      level: "N4",
      explain: ``,
      meaning: "Dự định/kế hoạch",
      usingWay: ``,
    },
    {
      id: "N4_108",
      romajiRead: "you desu",
      japaneseRead: "ようです",
      level: "N4",
      explain: ``,
      meaning: "Hình như/có lẽ...",
      usingWay: ``,
    },
    {
      id: "N4_109",
      romajiRead: "youni",
      japaneseRead: "ように",
      level: "N4",
      explain: ``,
      meaning: "Để làm gì đó...",
      usingWay: ``,
    },
    {
      id: "N4_110",
      romajiRead: "youni naru",
      japaneseRead: "ようになる",
      level: "N4",
      explain: ``,
      meaning: "Bắt đầu...",
      usingWay: ``,
    },
    {
      id: "N4_111",
      romajiRead: "youni suru",
      japaneseRead: "ようにする",
      level: "N4",
      explain: ``,
      meaning: "Sao cho/sao cho không",
      usingWay: ``,
    },
    {
      id: "N4_112",
      romajiRead: "zenzen～nai",
      japaneseRead: "全然～ない",
      level: "N4",
      explain: ``,
      meaning: "Hoàn toàn không...",
      usingWay: ``,
    },
    {
      id: "N4_113",
      romajiRead: "zurai",
      japaneseRead: "づらい",
      level: "N4",
      explain: ``,
      meaning: "Khó làm...",
      usingWay: ``,
    },
  ]);
}
