import { db } from "@/lib/drizzle/db";
import { grammars } from "@/lib/drizzle/seed/schema";

export async function InsertN1Grammars() {
  return await db.insert(grammars).values([
    {
      id: "N1_1",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_2",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_3",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_4",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_5",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_6",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_7",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_8",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_9",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_10",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_11",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_12",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_13",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_14",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_15",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_16",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_17",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_18",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_19",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_20",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_21",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_22",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_23",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_24",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_25",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_26",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_27",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_28",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_29",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_30",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_31",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_32",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_33",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_34",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_35",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_36",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_37",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_38",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_39",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_40",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_41",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_42",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_43",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_44",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_45",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_46",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_47",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_48",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_49",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_50",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_51",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_52",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_53",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_54",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_55",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_56",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_57",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_58",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_59",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_60",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_61",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_62",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_63",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_64",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_65",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_66",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_67",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_68",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_69",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_70",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_71",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N1_72",
      romajiRead: "",
      japaneseRead: "",
      level: "N1",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
  ]);
}
