import { db } from "@/lib/drizzle/db";
import { grammars } from "@/lib/drizzle/seed/schema";

export async function InsertN5Grammars() {
  return await db.insert(grammars).values([
    {
      id: "N5_1",
      romajiRead: "amari",
      japaneseRead: "あまり",
      level: "N5",
      explain: `『あまり』là phó từ biểu thị mức độ. Khi làm chức năng bổ nghĩa cho tính từ, động từ thì chúng được đặt trước tính từ, động từ.`,
      meaning: "Không...lắm",
      usingWay: `あまり ✙ Aくない<br/>あまり ✙ na Adj じゃない<br/>あまり ✙ Vない`,
    },
    {
      id: "N5_2",
      romajiRead: "da/desu",
      japaneseRead: "だ・です",
      level: "N5",
      explain: `『だ・です』Được đặt sau danh từ, tính từ đuôi “i” hoặc đuôi “na” làm vị ngữ, biểu thị sự phán đoán hay khẳng định của người nói về một sự việc nào đó.『です』biểu thị sự lịch sự của người nói đối với người nghe còn『だ』là thể rút gọn của『です』, đây là cách nói thân mật giữa những người thân, quen biết nhau.`,
      meaning: "Là...",
      usingWay: `Aい/na/N ✙ です<br/>Aい/na/N ✙ だ`,
    },
    {
      id: "N5_3",
      romajiRead: "dake",
      japaneseRead: "だけ",
      level: "N5",
      explain: `『だけ』Được đặt sau lượng từ hoặc danh từ để biểu thị ý nghĩa là “không nhiều hơn thế” hoặc “ngoài ra không có cái khác”.`,
      meaning: "Chỉ/thôi...",
      usingWay: `Lượng từ ✙ だけ、～<br/>Danh từ ✙ だけ、～`,
    },
    {
      id: "N5_4",
      romajiRead: "de",
      japaneseRead: "で",
      level: "N5",
      explain: `『～で』Diễn tả nơi xảy ra hành động, sự kiện.<br/>Diễn tả nguyên nhân, lý do xảy ra hành động.<br/>Diễn tả phương pháp, cách thức sự vật được làm bằng vật liệu, chất liệu gì.<br/>Diễn tả một khoảng thời gian giới hạn.`,
      meaning: "Tại/ở/vì/bằng/với",
      usingWay: `N ✙ で ～`,
    },
    {
      id: "N5_5",
      romajiRead: "demo",
      japaneseRead: "でも",
      level: "N5",
      explain:
        "『でも』Khi muốn đề nghị hoặc đề xuất một cái gì đó với người khác, chúng ta dùng trợ từ でも để biểu thị một thứ tượng trưng trong một nhóm các đối tượng thuộc cùng một phạm trù.",
      meaning: "Những thứ như.../hoặc là...gì đó",
      usingWay: `N ✙ でも ✙ V（普）`,
    },
    {
      id: "N5_6",
      romajiRead: "deshou",
      japaneseRead: "でしょう",
      level: "N5",
      explain:
        "『でしょう』Được dùng với giọng cao hơn để xác nhận sự đồng ý của người nghe về một vấn đề nào đó và mong muốn người nghe sẽ đồng ý với ý kiến của mình.",
      meaning: "Phải không...",
      usingWay: `Aい/V(普) ✙ でしょう<br/>na Adj(bỏ な) ✙ でしょう<br/>N(bỏ だ) ✙ でしょう`,
    },
    {
      id: "N5_7",
      romajiRead: "desuka",
      japaneseRead: "ですか",
      level: "N5",
      explain: `『ですか』Được dùng khi người nói nêu rõ đối tượng cần xác nhận và dùng mẫu câu này để xác nhận. Trợ từ［か］mang chức năng xác nhận.`,
      meaning: "À/phải không？",
      usingWay: `Aい/na/N/Vる ✙ ですか？<br/>［文］✙ ですか？`,
    },
    {
      id: "N5_8",
      romajiRead: "dono",
      japaneseRead: "どの",
      level: "N5",
      explain:
        "『どの』dùng để hỏi khi muốn xác định một đối tượng (vật hoặc người) nào đó trong một nhóm gồm 3 đối tượng trở lên.『どの』thì bắt buộc phải đi với danh từ còn『どれ』thì không cần, ngoài ra『どれ』chỉ được dùng để hỏi về vật, còn『どの』thì dùng được cho cả người và vật.",
      meaning: "...nào？",
      usingWay: `N ✙ どの`,
    },
    {
      id: "N5_9",
      romajiRead: "dono kurai",
      japaneseRead: "どのくらい",
      level: "N5",
      explain:
        "『どのくらい』Được dùng để hỏi về khoảng thời gian khi làm một việc nào đó.",
      meaning: "...khoảng bao lâu？",
      usingWay: `どのくらい ✙［文］～？<br/>どのくらい ✙ V（普）？`,
    },
    {
      id: "N5_10",
      romajiRead: "doushite",
      japaneseRead: "どうして",
      level: "N5",
      explain:
        "『どうして』Là nghi vấn từ, được dùng khi người nói muốn hỏi lý do, nguyên nhân của sự việc. Trong giao tiếp thông thường, nó còn mang sắc thái trách móc, phê bình nhẹ.『どうして』có thể sử dụng với cấp trên.",
      meaning: "Tại sao...",
      usingWay: `どうして ✙ ［文］～`,
    },
    {
      id: "N5_11",
      romajiRead: "douyatte",
      japaneseRead: "どうやって",
      level: "N5",
      explain:
        "『どうやって』Được dùng khi muốn hỏi về trình tự hoặc cách thức làm một việc gì đó.",
      meaning: "Làm thế nào/cách nào？",
      usingWay: `どうやって ✙ ［文］～`,
    },
    {
      id: "N5_12",
      romajiRead: "ga",
      japaneseRead: "が",
      level: "N5",
      explain: `『～が』Là trợ từ nối tiếp và có ý nghĩa là ” nhưng “.<br/>Khi dùng『～が』để nối 2 câu ( mệnh đề ) thì chúng ta được một câu.<br/>Khi muốn miêu tả một hiện tượng tự nhiên thì dùng『～が』trước chủ đề đó.`,
      meaning: "Nhưng",
      usingWay: `Aい / na / N / V ✙ が～<br/>『文』 ✙ が～`,
    },
    {
      id: "N5_13",
      romajiRead: "ga arimasu",
      japaneseRead: "があります",
      level: "N5",
      explain:
        "『があります』Mẫu câu này dùng để nói về nơi ở, sự hiện hữu của đồ vật, đối tượng được nhắc đến trong câu là những đồ vật không chuyển động được, sẽ làm chủ ngữ trong câu và được biểu thị bằng trợ từ が.",
      meaning: "Có...",
      usingWay: `N ✙ があります`,
    },
    {
      id: "N5_14",
      romajiRead: "ga hoshii desu",
      japaneseRead: "がほしいです",
      level: "N5",
      explain: `『がほしいです』Mẫu câu biểu thị ham muốn sở hữu một vật hoặc một người nào đó của người nói. Nó cũng được dùng để hỏi về ham muốn của người nghe.<br/>『がほしいですが．．．』Mẫu câu này có thể dùng để thể hiện mong muốn với người đối diện để người đó đáp ứng cho mình.`,
      meaning: "Muốn...",
      usingWay: `N ✙ がほしいです`,
    },
    {
      id: "N5_15",
      romajiRead: "ga ichiban...desu",
      japaneseRead: "がいちばん…です",
      level: "N5",
      explain:
        "『がいちばん…です』Mẫu câu này dùng để nói về sự lựa chọn của người nói. Trong số những đối tượng đó (vật/địa điểm/người/thời điểm) có nội dung được biểu thị qua tính từ ở mức độ cao nhất.",
      meaning: "Nhất là...",
      usingWay: `N がいちばん Aいです`,
    },
    {
      id: "N5_16",
      romajiRead: "ga imasu",
      japaneseRead: "がいます",
      level: "N5",
      explain:
        "『がいます』Mẫu câu này dùng để nói về nơi ở, sự hiện hữu của người hoặc vật, đối tượng được nhắc đến trong câu là những đối tượng có thể chuyển động được như người hoặc động vật.",
      meaning: "Có...",
      usingWay: `N ✙ がいます`,
    },
    {
      id: "N5_17",
      romajiRead: "gurai",
      japaneseRead: "ぐらい",
      level: "N5",
      explain:
        "『ぐらい』Được thêm vào sau lượng từ chỉ số lượng để biểu thị ý là “khoảng…”, sử dụng trong trường hợp người nói không thể đưa ra được con số chính xác mà chỉ là ước chừng, đại khái là như vậy…",
      meaning: "Khoảng...",
      usingWay: `Lượng từ (số lượng) ✙ ぐらい`,
    },
    {
      id: "N5_18",
      romajiRead: "issho ni",
      japaneseRead: "一緒に",
      level: "N5",
      explain:
        "『一緒に』Là phó từ mang ý nghĩa là “cùng/cùng nhau”, diễn tả ý cùng với ai đó làm việc gì đó.",
      meaning: "	Cùng/cùng với...",
      usingWay: `一緒に ✙ V（普）`,
    },
    {
      id: "N5_19",
      romajiRead: "itsu",
      japaneseRead: "いつ",
      level: "N5",
      explain:
        "『いつ』Được dùng khi muốn hỏi về thời điểm thực hiện một hành động nào đó. Đối với『いつ』thì không dùng trợ từ『に』ở phía sau và đây cũng là cách để phân biệt『いつ』với những nghi vấn từ khác.",
      meaning: "Khi nào/bao giờ...",
      usingWay: `いつ ✙ ［文］～`,
    },
    {
      id: "N5_20",
      romajiRead: "itsumo",
      japaneseRead: "いつも",
      level: "N5",
      explain:
        "『いつも』Diễn tả một hành động, một thói quen thường xuyên xảy ra.",
      meaning: "Lúc nào cũng/luôn...",
      usingWay: `いつも ✙［文］`,
    },
    {
      id: "N5_21",
      romajiRead: "janai / dewa nai",
      japaneseRead: "じゃない・ではない",
      level: "N5",
      explain:
        "『じゃない・ではない』là thể phủ định của［です］, phủ định một sự việc nào đó không phải là…và được dùng nhiều trong giao tiếp hàng ngày.［ではない］được dùng trong văn viết hoặc các bài phát biểu trang trọng.",
      meaning: "Không phải là...",
      usingWay: `N ✙ じゃない<br/>N ✙ ではない`,
    },
    {
      id: "N5_22",
      romajiRead: "ka",
      japaneseRead: "か",
      level: "N5",
      explain:
        "『か』Trợ từ này được dùng để biểu thị sự không chắc chắn, sự nghi vấn của người nói về một sự việc nào đó.",
      meaning: "Phải không/hả/à？",
      usingWay: `Aい /Aな /N /Vる ✙ か<br/>［文］✙ か`,
    },
    {
      id: "N5_23",
      romajiRead: "ka∼ka",
      japaneseRead: "か～か",
      level: "N5",
      explain:
        "『か～か』Mẫu câu nghi vấn này dùng để hỏi về sự lựa chọn của người nghe. Người nghe sẽ lựa chọn câu trả lời ở vế trước hoặc là vế sau.",
      meaning: "...là...hay là？",
      usingWay: `［文］ か、［文］ か`,
    },
    {
      id: "N5_24",
      romajiRead: "kara",
      japaneseRead: "から",
      level: "N5",
      explain:
        "『から』Là mẫu câu được dùng để giải thích nguyên nhân, lý do dẫn đến sự việc như thế.",
      meaning: "Vì/bởi vì...",
      usingWay: `V（普）/Vます ✙ から、～<br/>Aいです ✙ から、～<br/>na/N だ/です  ✙ から、～`,
    },
    {
      id: "N5_25",
      romajiRead: "kara～made",
      japaneseRead: "から～まで",
      level: "N5",
      explain:
        "『から』biểu thị điểm bắt đầu và 『まで』biểu thị điểm kết thúc của thời gian và địa điểm.",
      meaning: "Từ～đến",
      usingWay: `N から ～ N まで`,
    },
    {
      id: "N5_26",
      romajiRead: "kedo",
      japaneseRead: "けど",
      level: "N5",
      explain:
        "『けど』Được dùng để nối 2 vế câu có ý nghĩa trái ngược, tương phản nhau. Mẫu câu này được dùng nhiều trong hội thoại thường ngày.",
      meaning: "Mặc dù...nhưng...",
      usingWay: `A/na/N/Vる ✙ けど`,
    },
    {
      id: "N5_27",
      romajiRead: "koto ga aru",
      japaneseRead: "ことがある",
      level: "N5",
      explain:
        "『ことがある』Mẫu câu này được dùng để biểu thị ai đó đã từng làm một việc nào đó trong qua khứ.",
      meaning: "Đã từng...",
      usingWay: `Vた ✙ ことがある`,
    },
    {
      id: "N5_28",
      romajiRead: "koto ga dekimasu",
      japaneseRead: "ことができます",
      level: "N5",
      explain: `『できます』là động từ biểu thị năng lực hoặc khả năng. Cụm từ đặt trước『が』gồm danh từ『động từ thể nguyên dạngこと』biểu thị nội dung của năng lực hoặc khả năng.`,
      meaning: "Có thể...",
      usingWay: `N ✙ ができます<br/>Vること ✙ ができます`,
    },
    {
      id: "N5_29",
      romajiRead: "kuremasu",
      japaneseRead: "くれます",
      level: "N5",
      explain: `『くれます』Cũng giống như『もらいます』, mẫu câu này biểu thị sự biết ơn của bên tiếp nhận hành vi. Sự khác biệt giữa 2 cấu trúc này đấy là:<br/>『もらいます』Chủ ngữ là đối tượng tiếp nhận hành vi, được ai đó làm cái gì đó cho…<br/>『くれます』 Chủ ngữ là đối tượng thực hiện hành vi, trong trường hợp đối tượng tiếp nhận hành vi là bản thân người nói thì phần『わたしに』bị lược bỏ.`,
      meaning: "...Cho tôi",
      usingWay: `Vて ✙ くれます`,
    },
    {
      id: "N5_30",
      romajiRead: "made ni",
      japaneseRead: "までに",
      level: "N5",
      explain:
        "『までに』Mẫu câu này biểu thị thời hạn mà động tác hay hành động cần phải thực hiện. Hay nói cách khác cần phải thực hiện động tác hay hành động trước thời điểm được biểu thị bằng までに.",
      meaning: "Trước...",
      usingWay: `N (thời gian) ✙ までに`,
    },
    {
      id: "N5_31",
      romajiRead: "mae ni",
      japaneseRead: "まえに",
      level: "N5",
      explain: `『まえに』<br/>1. Trường hợp của động từ: Mẫu câu này biểu thị rằng động tác ở động từ 2 xảy ra trước động từ 1. Động từ 1 luôn ở thể nguyên dạng cho dù động từ 2 có ở thời quá khứ hay tương lai.<br/>2. Trường hợp của danh từ: Khi dùng『まえに』sau danh từ chúng ta phải thêm の vào. Danh từ ở trước『まえに』là danh từ biểu thị hoặc ám chỉ động tác.<br/>3. Trường hợp của lượng từ: Nếu là lượng từ (khoảng thời gian) thì không thêm の.`,
      meaning: "Trước khi...",
      usingWay: `V₁(thể thông thường) ✙ まえに、V₂<br/>Danh từ の  ✙ まえに、V<br/>Lượng từ(khoảng thời gian) ✙ まえに、V`,
    },
    {
      id: "N5_32",
      romajiRead: "masen ka",
      japaneseRead: "ませんか",
      level: "N5",
      explain: `『ませんか』Mẫu câu này dùng để mời hoặc đề nghị người nghe làm một việc gì đó、vừa hỏi ý người nghe vừa bày tỏ nguyện vọng của người nói rằng ” nếu người nghe đồng ý thì tốt biết mấy “.<br/>Thường đi cùng với 『一緒に』.`,
      meaning: "Cùng...với tôi không ?",
      usingWay: `V(bỏ ます) ✙ ませんか`,
    },
    {
      id: "N5_33",
      romajiRead: "mashou",
      japaneseRead: "ましょう",
      level: "N5",
      explain: `『ましょう』Mẫu câu này dùng để đề nghị, rủ rê hay kêu gọi người nghe cùng làm một việc gì đó với người nói. Nó thể hiện thái độ chủ động của người nói.<br/>『ましょう』và 『ませんか』đều là những cách nói để mời ai đó làm gì. So với 『ましょう』thì 『ませんか』thể hiện ít nhiều sự rụt rè, giữ ý của người nói đối với người nghe.`,
      meaning: "Hãy cùng...",
      usingWay: `V(bỏ ます) ✙ ましょう`,
    },
    {
      id: "N5_34",
      romajiRead: "mashou ka",
      japaneseRead: "ましょうか",
      level: "N5",
      explain:
        "『ましょうか』Mẫu câu này dùng khi người nói muốn nêu ra đề nghị làm một việc gì đó cho người nghe.",
      meaning: "...nhé.",
      usingWay: `V(bỏ ます) ✙ ましょうか`,
    },
    {
      id: "N5_35",
      romajiRead: "mo",
      japaneseRead: "も",
      level: "N5",
      explain:
        "『も』Được dùng khi danh từ diễn tả chủ đề của câu giống với danh từ tương ứng ở câu trước.",
      meaning: "Cũng...",
      usingWay: `N ✙ も`,
    },
    {
      id: "N5_36",
      romajiRead: "morai masu",
      japaneseRead: "もらいます",
      level: "N5",
      explain:
        "『もらいます』Dùng để biểu thị sự biết ơn, cảm kích ai đó đã làm việc gì đó cho mình, cho người tiếp nhận hành vi.",
      meaning: "...Cho tôi",
      usingWay: `Vて ✙ もらいます`,
    },
    {
      id: "N5_37",
      romajiRead: "moshi/ikura",
      japaneseRead: "もし・いくら",
      level: "N5",
      explain: `『もし/いくら』<br/>『もし』được dùng để nhấn mạnh ý kiến của người nói trong điều kiện được giả định và luôn đi cùng với たら, còn『いくら』nhấn mạnh mức độ của điều kiện và đi cùng với ても/でも.`,
      meaning: "Nếu.../Cho dù...",
      usingWay: `もし  ✙ たら ～<br/>いくら ✙ ても/でも ～`,
    },
    {
      id: "N5_38",
      romajiRead: "mou",
      japaneseRead: "もう",
      level: "N5",
      explain: `『もう』Có ý nghĩa là “đã/rồi…” việc gì đó, tùy vào danh từ hay thì ở vế phía sau mà nội dung của câu sẽ thay đổi.<br/>1. Nếu ở vế phía sau là động từ ở thể quá khứ thì もう biểu thị một hành động nào đó đã kết thúc ở thời điểm hiện tại.<br/>2. Nếu ở vế phía sau là động từ ở thể phủ định thì もう biểu thị ý nữa/không lần nào nữa/không thể nữa.<br/>3. Nếu ở vế phía sau là danh từ chỉ thời gian thì もう biểu thị ý đã đến thời điểm được nhắc đến rồi.`,
      meaning: "Đã...rồi/nữa/không thể nữa...",
      usingWay: `もう ✙ N/V（普）`,
    },
    {
      id: "N5_39",
      romajiRead: "naide kudasai",
      japaneseRead: "ないでください",
      level: "N5",
      explain:
        "『ないでください』Mẫu câu này dùng khi muốn yêu cầu ai đó đừng làm một việc nào đó.",
      meaning: "Xin đừng.../không...",
      usingWay: `Vない ✙ ないでください`,
    },
    {
      id: "N5_40",
      romajiRead: "naito",
      japaneseRead: "ないと",
      level: "N5",
      explain:
        "『ないと』Mẫu câu này được dùng khi muốn thể hiện là phải làm một việc gì đó. Đây là cách nói ngắn gọn của mẫu câu『ないといけません』.",
      meaning: "Phải làm gì đó...",
      usingWay: `V(bỏ ない) ✙ ないと`,
    },
    {
      id: "N5_41",
      romajiRead: "nakanaka",
      japaneseRead: "なかなか",
      level: "N5",
      explain:
        "『なかなか』Là phó từ biểu thị mức độ, luôn đi cùng với động từ ở thể phủ định và diễn tả ý ” không dễ gì ” hoặc ” không đúng như mong đợi “, diễn tả một tình trạng nào đó mãi mà không thể thực hiện được.",
      meaning: "Khó mà/mãi mà...",
      usingWay: `なかなか ✙ Vない`,
    },
    {
      id: "N5_42",
      romajiRead: "nakereba narimasen",
      japaneseRead: "なければなりません",
      level: "N5",
      explain:
        "『なければなりません』Mẫu câu này biểu thị rằng một đối tượng nào đó phải làm một việc gì đó mà không phụ thuộc vào ý muốn của đối tượng thực hiện hành động. Lưu ý là mẫu câu này không mang ý nghĩa phủ định.",
      meaning: "Phải...",
      usingWay: `Vない(bỏ ない) ✙ なければなりません`,
    },
    {
      id: "N5_43",
      romajiRead: "nakutemo ii desu",
      japaneseRead: "なくてもいいです",
      level: "N5",
      explain:
        "『なくてもいいです』Mẫu câu này biểu thị đối tượng nào đó không phải làm việc gì đó.",
      meaning: "Không cần phải...",
      usingWay: `Vない(bỏ ない) ✙ なくてもいいです`,
    },
    {
      id: "N5_44",
      romajiRead: "narimasu",
      japaneseRead: "なります",
      level: "N5",
      explain:
        "『なります』Mang nghĩa là “trở thành, trở nên”, nó biểu thị sự thay đổi về trạng thái.",
      meaning: "Trở nên...",
      usingWay: `Aい(bỏ い)く ✙ なります<br/>na Adjな に✙ なります<br/>Nに ✙ なります`,
    },
    {
      id: "N5_45",
      romajiRead: "ne",
      japaneseRead: "ね",
      level: "N5",
      explain:
        "『ね 』Được thêm vào cuối câu để biểu thị sự thông cảm, đồng tình của người nói đối với người nghe. Cũng có khi nó còn được dùng để thể hiện sự kỳ vọng của người nói vào sự đồng ý của người nghe hay là mang chức năng xác nhận (ý kiến/thái độ của người nghe).",
      meaning: "Nhỉ/nhé/quá...",
      usingWay: `［文］ ✙ ね`,
    },
    {
      id: "N5_46",
      romajiRead: "ni",
      japaneseRead: "に",
      level: "N5",
      explain:
        "『に』Được dùng khi muốn nói về thời điểm mà một hành động nào đó xảy ra.",
      meaning: "Lúc/vào...",
      usingWay: `N ✙ に ✙ V（普）`,
    },
    {
      id: "N5_47",
      romajiRead: "ni iku",
      japaneseRead: "にいく",
      level: "N5",
      explain:
        "『にいく』Được dùng để diễn tả ý đi đâu đó để làm việc gì đó, đi với mục đích gì đó… Danh từ ở mẫu câu này là những từ chỉ phương hướng hoặc địa điểm.",
      meaning: "Đi làm gì đó...",
      usingWay: `N ✙ にいく`,
    },
    {
      id: "N5_48",
      romajiRead: "ni/he",
      japaneseRead: "に・へ",
      level: "N5",
      explain:
        "『に/へ』Được dùng để chỉ địa điểm, phương hướng, nơi diễn ra sự việc hay là chỉ một hành động hướng về phía nào đó. Danh từ đứng trước に/へ phải là từ chỉ địa điểm, nơi chốn.",
      meaning: "Ở/đến…",
      usingWay: `N ✙ に/へ ✙ V（普）`,
    },
    {
      id: "N5_49",
      romajiRead: "no",
      japaneseRead: "の",
      level: "N5",
      explain:
        "『の』Dùng để nối 2 danh từ lại với nhau, danh từ số 1 bổ nghĩa cho danh từ số 2.『の』trong cấu trúc này biểu thị tính sở hữu của chủ thể được nhắc đến.",
      meaning: "Của...",
      usingWay: `N1 ✙ の ✙ N2`,
    },
    {
      id: "N5_50",
      romajiRead: "no ga heta",
      japaneseRead: "のが下手",
      level: "N5",
      explain:
        "『のが下手』Mẫu câu này diễn tả ý người nói rất kém, rất dở khi làm một việc gì đấy và sự việc đó được biểu đạt bằng động từ đứng trước のが下手. Chức năng của『の』trong mẫu câu này trợ từ biến động từ trở thành danh từ.",
      meaning: "Dở/kém/không giỏi ～ (việc gì đó)",
      usingWay: `Vる ✙ のが下手`,
    },
    {
      id: "N5_51",
      romajiRead: "～ no naka de ～ ga ichiban",
      japaneseRead: "～の中で～が一番",
      level: "N5",
      explain:
        "『の中で～が一番』Mẫu câu này dùng để yêu cầu người nghe lựa chọn một đối tượng nào đó có nội dung được biểu thị qua tính từ ở mức độ cao nhất.",
      meaning: "Trong... thì... nhất là gì？",
      usingWay: `N1 の中で 「何/どこ/だれ/いつ」 が一番  Aい`,
    },
    {
      id: "N5_52",
      romajiRead: "no ga jouzu",
      japaneseRead: "のが上手",
      level: "N5",
      explain:
        "『のが上手』Mẫu câu này diễn tả ý người nói rất giỏi khi làm một việc gì đấy và sự việc đó được biểu đạt bằng động từ đứng trước のが上手. Chức năng của『の』trong mẫu câu này trợ từ biến động từ trở thành danh từ.",
      meaning: "Giỏi ～ (việc gì đó)",
      usingWay: `Vる ✙ のが上手`,
    },
    {
      id: "N5_53",
      romajiRead: "wo",
      japaneseRead: "を",
      level: "N5",
      explain:
        "『を』Trợ từ này được dùng để bổ nghĩa cho động từ, nhấn mạnh sự việc đang được nói đến trong câu. Ngoài ra còn được dùng để biểu thị địa điểm mà người hoặc vật đi qua.",
      meaning: "Làm(gì đó)/ở...",
      usingWay: `N ✙ を ✙ V（普）`,
    },
    {
      id: "N5_54",
      romajiRead: "ta kotoga aru",
      japaneseRead: "たことがある",
      level: "N5",
      explain: `『たことがある』Cấu trúc này được sử dụng để diễn tả về kinh nghiệm đã từng hoặc chưa từng làm gì đó.<br/>Thể khẳng định ( たことがある ): đã từng làm gì đó.<br/>Thể phủ định ( たことがない ): chưa từng làm gì đó.`,
      meaning: "Đã từng",
      usingWay: `Vた ✙ ことがある<br/>Vた ✙ ことがない`,
    },
    {
      id: "N5_55",
      romajiRead: "tai desu",
      japaneseRead: "たいです",
      level: "N5",
      explain: `『たいです』Đây là cách nói biểu thị sự “muốn làm” một cái gì đó. Cách nói này được dùng để biểu thị ý muốn của bản thân người nói, và để hỏi về ý muốn của người nghe.<br/>『Vたい』ở thể phủ định chia tương tự như tính từ đuôi Aい`,
      meaning: "Muốn...",
      usingWay: `V(bỏ ます) ✙ たいです`,
    },
    {
      id: "N5_56",
      romajiRead: "tara",
      japaneseRead: "たら",
      level: "N5",
      explain: `『たら』Mẫu câu này được dùng khi người nói muốn biểu thị ý kiến, tình trạng, yêu cầu của mình trong trường hợp được giả định.`,
      meaning: "Nếu...thì...",
      usingWay: `Vた ✙ ら、～<br/>A(bỏ い)かった ✙ ら、～<br/>na Adj(bỏ な)だった ✙ ら、～<br/>N だった  ✙ ら、～`,
    },
    {
      id: "N5_57",
      romajiRead: "tara",
      japaneseRead: "たら",
      level: "N5",
      explain:
        "『たら』Mẫu câu này biểu thị 1 động tác hay hành vi nào đó sẽ được làm, hoặc 1 tình huống nào đó sẽ xảy ra sau khi 1 việc, 1 động tác hay 1 trạng thái nào đó chắc chắn sẽ diễn ra trong tương lai.",
      meaning: "Sau khi...",
      usingWay: `Vた ✙ ら、～`,
    },
    {
      id: "N5_58",
      romajiRead: "tari～tari",
      japaneseRead: "たり～たり",
      level: "N5",
      explain:
        "『たり～たり』Mẫu câu này được dùng khi muốn nêu ra, liệt kê một số động tác trong một nhóm nhiều động tác. Trong mẫu câu này thì của động từ được biểu hiện ở cuối câu.",
      meaning: "Làm...làm...",
      usingWay: `～V(bỏ )たり、～V(bỏ )たり します`,
    },
    {
      id: "N5_59",
      romajiRead: "te ageru",
      japaneseRead: "てあげる",
      level: "N5",
      explain: `『てあげる』Dùng để biểu thị một người nào đó làm việc tốt cho ai đó với thiện ý.`,
      meaning: "Cho ai đó...",
      usingWay: `Vて ✙ あげる`,
    },
    {
      id: "N5_60",
      romajiRead: "te iru",
      japaneseRead: "ている",
      level: "N5",
      explain: `『ている』Cấu trúc này được dùng vào những trường hợp như sau:<br/>1. Biểu thị một hàng động đang diễn ra.<br/>2. Diễn tả một trạng thái (là kết quả của một hành động) vẫn còn lại, vẫn tiếp diễn ở hiện tại.<br/>3. Được dùng để nói về các tập quán, thói quen (tức là những hành vi được lặp đi lặp lại trong 1 thời gian dài).`,
      meaning: "Đang...",
      usingWay: `Vて ✙ いる<br/>て ✙ いない<br/>Vて ✙ います<br/>Vて ✙ いません`,
    },
    {
      id: "N5_61",
      romajiRead: "te kara",
      japaneseRead: "てから",
      level: "N5",
      explain:
        "『てから』Mẫu câu này dùng để biểu thị rằng hành động ở động từ 2 được thực hiện sau khi hành động ở động từ 1 kết thúc.",
      meaning: "Sau khi...",
      usingWay: `V₁て ✙ から、V₂`,
    },
    {
      id: "N5_62",
      romajiRead: "te kudasai",
      japaneseRead: "てください",
      level: "N5",
      explain: `『てください』Mẫu câu này được dùng khi người nói muốn nhờ vả, sai khiến hoặc khuyên nhủ người nghe.<br/>Khi nói với cấp trên, người lớn tuổi thì không dùng mẫu câu này với ý nghĩa sai khiến.`,
      meaning: "Hãy làm gì",
      usingWay: `Vて ✙ ください`,
    },
    {
      id: "N5_63",
      romajiRead: "temo",
      japaneseRead: "ても",
      level: "N5",
      explain:
        "『ても』Mẫu câu này được dùng khi 1 hành động nào đó trong 1 hoàn cảnh nhất định đáng ra phải làm nhưng lại không làm, 1 việc nào đó đáng ra phải xảy ra nhưng lại không xảy ra, hoặc 1 kết quả trái với quan niệm thông thường của mọi người.",
      meaning: "Dù...cũng...",
      usingWay: `Vて ✙ も、～<br/>A(bỏ い)くて ✙ も、～<br/>na Adjなで ✙ も、～<br/>N で  ✙ も、～`,
    },
    {
      id: "N5_64",
      romajiRead: "temo ii desu",
      japaneseRead: "てもいいです",
      level: "N5",
      explain:
        "『てもいいです』Mẫu câu này dùng để biểu thị sự được cho phép làm một điều gì đó. Nếu chuyển mẫu câu này thành câu nghi vấn thì chúng ta sẽ được một câu xin phép.",
      meaning: "Làm...được...",
      usingWay: `Vて ✙ もいいです`,
    },
    {
      id: "N5_65",
      romajiRead: "tewa ikemasen",
      japaneseRead: "てはいけません",
      level: "N5",
      explain:
        "『てはいけません』Mẫu câu này biểu thị ý nghĩa “cấm”, hay “không được” làm một việc gì đó.",
      meaning: "Không được làm...",
      usingWay: `Vて ✙ はいけません`,
    },
    {
      id: "N5_66",
      romajiRead: "to",
      japaneseRead: "と",
      level: "N5",
      explain:
        "『と』Dùng để nối 2 mệnh đề của câu để biểu thị một kết quả tất yếu của một hành động nào đó. Mệnh đề phía sau không dùng để biểu thị ý muốn, nguyện vọng, lời mời hoặc yêu cầu.",
      meaning: "Là.../thì...",
      usingWay: `Vる ✙ と`,
    },
    {
      id: "N5_67",
      romajiRead: "to iimasu",
      japaneseRead: "と言います",
      level: "N5",
      explain: `『と言います』<br/>1. Được dùng khi muốn trích dẫn trực tiếp lời nói của ai đó, phần trích dẫn được để trong『』.<br/>2. Dùng khi muốn trích dẫn gián tiếp, nhắc lại lời ai đó đã nói. Động từ được chia ở thể thông thường và không dùng『』.`,
      meaning: "Nói/nói rằng...",
      usingWay: `［文］ ✙ と言います<br/>V(普) ✙ と言います`,
    },
    {
      id: "N5_68",
      romajiRead: "to omoimasu",
      japaneseRead: "と思います",
      level: "N5",
      explain:
        "『と思います』Dùng để biểu thị sự phán đoán, suy xét hoặc bày tỏ ý kiến của người nói về một vấn đề nào đó.",
      meaning: "Tôi nghĩ là...",
      usingWay: `Aい/V(普) ✙ と思います<br/>na Adj(bỏ な) ✙ と思います<br/>Nだ ✙ と思います`,
    },
    {
      id: "N5_69",
      romajiRead: "toki",
      japaneseRead: "とき",
      level: "N5",
      explain:
        "『とき』Dùng để nối 2 mệnh đề của câu. Nó biểu thị thời điểm mà trạng thái, động tác hay hiện tượng được diễn đạt ở mệnh đề sau diễn ra.",
      meaning: "Khi...",
      usingWay: `Aい/V(普)/Vない ✙ とき、～<br/>na Adj な ✙ とき、～<br/>N の  ✙ とき、～`,
    },
    {
      id: "N5_70",
      romajiRead: "totemo",
      japaneseRead: "とても",
      level: "N5",
      explain:
        "『とても』Là phó từ biểu thị mức độ và đứng trước tính từ để bổ nghĩa cho tính từ. Luôn được dùng trong các câu khẳng định.",
      meaning: "Rất...",
      usingWay: `とても ✙ Aい<br/>とても ✙ na Adj な`,
    },
    {
      id: "N5_71",
      romajiRead: "wa",
      japaneseRead: "は",
      level: "N5",
      explain:
        "『は』Trợ từ này được dùng để biểu thị rằng danh từ đứng trước nó là chủ đề của câu. Người nói đặt『は』trước chủ đề mà mình muốn nói đến và lập thành câu bằng cách thêm vào sau『は』những thông tin cần thiết.",
      meaning: "Là...",
      usingWay: `N ✙ は ～`,
    },
    {
      id: "N5_72",
      romajiRead: "wa dou desuka",
      japaneseRead: "はどうですか",
      level: "N5",
      explain:
        "『はどうですか？』Cấu trúc này được dùng để hỏi về cảm nghĩ, cảm tưởng, ấn tượng của người nghe về một sự việc nào đấy.",
      meaning: "...thế nào？ như thế nào rồi？",
      usingWay: `N ✙ はどうですか？`,
    },
    {
      id: "N5_73",
      romajiRead: "wa～yori...desu",
      japaneseRead: "は～より…です",
      level: "N5",
      explain:
        "『は～より…です』Đây là cách nói so sánh lấy danh từ số 2 làm tiêu chuẩn để nói về tính chất hoặc trạng thái của danh từ số 1. Mẫu câu này dùng để nhấn mạnh danh từ số 1.",
      meaning: "...hơn...",
      usingWay: `N1 は N2 より A です`,
    },
    {
      id: "N5_74",
      romajiRead: "ya",
      japaneseRead: "や",
      level: "N5",
      explain:
        "『や』Trợ từ này được dùng khi muốn liệt kê các danh từ. Nếu như trợ từ と được dùng để liệt kê hết tất cả các đối tượng, thì trợ từ や được dùng để liệt kê một số đối tượng tiêu biểu (2 danh từ trở lên) mà thôi. Có thể sử dụng trợ từ など ở cuối danh từ để biểu thị rõ rằng còn có những đối tượng khác ngoài đối tượng được nêu.",
      meaning: "Như là...",
      usingWay: `N1 ✙ や ✙ N2`,
    },
    {
      id: "N5_75",
      romajiRead: "yo",
      japaneseRead: "よ",
      level: "N5",
      explain:
        "『よ』Được đặt ở cuối câu để nhấn mạnh một thông tin nào đó mà người nghe chưa biết, hoặc để nhấn mạnh ý kiến hoặc sự phán đoán của người nói đối với người nghe.",
      meaning: "Đấy/nhé/cơ...",
      usingWay: `［文］✙ よ`,
    },
    {
      id: "N5_76",
      romajiRead: "yori～nohou ga",
      japaneseRead: "より～のほうが",
      level: "N5",
      explain:
        "『より～のほうが』Đây là cách nói đảo ngược lại trật tự của hai danh từ, còn về ý nghĩa thì N1 vẫn ở mức độ cao hơn so với N2.",
      meaning: "So với～thì",
      usingWay: `N2 より N1 のほうが．．．`,
    },
    {
      id: "N5_77",
      romajiRead: "zehi",
      japaneseRead: "ぜひ",
      level: "N5",
      explain:
        "『ぜひ』được dùng để thể hiện ý chí của người nói, quyết tâm vượt qua khó khăn để thực hiện việc gì đó. Ngoài ra còn được để thể hiện nguyện vọng, yêu cầu của người nói khi đề nghị ai đó làm việc gì đó.",
      meaning: "Nhất định/thế nào cũng phải...",
      usingWay: `ぜひ ✙ ［文］～`,
    },
  ]);
}
