import { db } from "@/lib/drizzle/db";
import { grammars } from "@/lib/drizzle/schema";

export async function InsertN2Grammars() {
  return await db.insert(grammars).values([
    {
      id: "N2_1",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_2",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_3",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_4",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_5",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_6",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_7",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_8",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_9",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_10",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_11",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_12",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_13",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_14",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_15",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_16",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_17",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_18",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_19",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_20",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_21",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_22",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_23",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_24",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_25",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_26",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_27",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_28",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_29",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_30",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_31",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_32",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_33",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_34",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_35",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_36",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_37",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_38",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_39",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_40",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_41",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_42",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_43",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_44",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_45",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_46",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_47",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_48",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_49",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_50",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_51",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_52",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_53",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_54",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_55",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_56",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_57",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_58",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_59",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_60",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_61",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_62",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_63",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_64",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_65",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_66",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_67",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_68",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_69",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_70",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_71",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_72",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_73",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_74",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_75",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_76",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_77",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_78",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_79",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_80",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_81",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_82",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_83",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_84",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_85",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_86",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_87",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_88",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_89",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_90",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_91",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_92",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_93",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_94",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_95",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_96",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_97",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_98",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_99",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_100",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_101",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_102",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_103",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_104",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_105",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_106",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_107",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_108",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_109",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_110",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_111",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_112",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_113",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_114",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_115",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_116",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_117",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_118",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_119",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_120",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_121",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_122",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_123",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_124",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_125",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_126",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_127",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_128",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_129",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_130",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_131",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_132",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_133",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_134",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_135",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_136",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_137",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_138",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_139",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_140",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_141",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_142",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_143",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_144",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_145",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_146",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_147",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_148",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_149",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_150",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_151",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_152",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_153",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_154",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_155",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_156",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_157",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_158",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_159",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_160",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_161",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_162",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_163",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_164",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_165",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_166",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_167",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_168",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_169",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_170",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_171",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_172",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_173",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_174",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_175",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_176",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_177",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_178",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_179",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_180",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_181",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_182",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_183",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_184",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_185",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_186",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_187",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_188",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_189",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_190",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_191",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_192",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_193",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_194",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_195",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_196",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_197",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_198",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_199",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_200",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_201",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_202",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_203",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_204",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_205",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_206",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_207",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_208",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_209",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_210",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_211",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_212",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_213",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_214",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_215",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_216",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_217",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_218",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_219",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_220",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_221",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_222",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_223",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_224",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_225",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_226",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_227",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_228",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
    {
      id: "N2_229",
      romajiRead: "",
      japaneseRead: "",
      level: "N2",
      explain: ``,
      meaning: "",
      usingWay: ``,
    },
  ]);
}
